live_config_reload = true
working_directory = "None"

[bell]
animation = "EaseOutExpo"
color = "0xffffff"
duration = 0

[colors]
draw_bold_text_with_bright_colors = true

[colors.bright]
black = "#5c6370"
blue = "#61afef"
cyan = "#56b6c2"
green = "#98c379"
magenta = "#c678dd"
red = "#e06c75"
white = "#ffffff"
yellow = "#d19a66"

[colors.normal]
black = "#282c34"
blue = "#61afef"
cyan = "#56b6c2"
green = "#98c379"
magenta = "#c678dd"
red = "#e06c75"
white = "#abb2bf"
yellow = "#d19a66"

[colors.primary]
background = "#282c34"
foreground = "#abb2bf"

[cursor]
unfocused_hollow = true

[debug]
log_level = "Warn"
persistent_logging = false
print_events = false
render_timer = false

[env]
TERM = "xterm-256color"
WINIT_X11_SCALE_FACTOR = "1.0"

[font]
size = 10.0

[font.glyph_offset]
x = 0
y = 0

[font.offset]
x = 0
y = 0

[[keyboard.bindings]]
action = "Paste"
key = "V"
mods = "Control|Shift"

[[keyboard.bindings]]
action = "Copy"
key = "C"
mods = "Control|Shift"

[[keyboard.bindings]]
action = "Paste"
key = "V"
mods = "Control|Alt"

[[keyboard.bindings]]
action = "Copy"
key = "C"
mods = "Control|Alt"

[[keyboard.bindings]]
action = "Paste"
key = "Paste"

[[keyboard.bindings]]
action = "Copy"
key = "Copy"

[[keyboard.bindings]]
action = "Quit"
key = "Q"
mods = "Command"

[[keyboard.bindings]]
action = "Quit"
key = "W"
mods = "Command"

[[keyboard.bindings]]
action = "PasteSelection"
key = "Insert"
mods = "Shift"

[[keyboard.bindings]]
action = "ResetFontSize"
key = "Key0"
mods = "Control"

[[keyboard.bindings]]
action = "IncreaseFontSize"
key = "Equals"
mods = "Control"

[[keyboard.bindings]]
action = "IncreaseFontSize"
key = "Plus"
mods = "Control|Shift"

[[keyboard.bindings]]
action = "DecreaseFontSize"
key = "Minus"
mods = "Control"

[[keyboard.bindings]]
action = "ClearLogNotice"
key = "L"
mods = "Control"

[[keyboard.bindings]]
chars = "\f"
key = "L"
mods = "Control"

[[keyboard.bindings]]
chars = "\u001B[13;2u"
key = "Return"
mods = "Shift"

[[keyboard.bindings]]
chars = "\u001B[13;5u"
key = "Return"
mods = "Control"

[[keyboard.bindings]]
chars = "\u001B[32;2u"
key = "Space"
mods = "Shift"

[[keyboard.bindings]]
chars = "\u001BOH"
key = "Home"
mode = "AppCursor"

[[keyboard.bindings]]
chars = "\u001B[H"
key = "Home"
mode = "~AppCursor"

[[keyboard.bindings]]
chars = "\u001BOF"
key = "End"
mode = "AppCursor"

[[keyboard.bindings]]
chars = "\u001B[F"
key = "End"
mode = "~AppCursor"

[[keyboard.bindings]]
chars = "\u001B[5;2~"
key = "PageUp"
mods = "Shift"

[[keyboard.bindings]]
chars = "\u001B[5;5~"
key = "PageUp"
mods = "Control"

[[keyboard.bindings]]
chars = "\u001B[5~"
key = "PageUp"

[[keyboard.bindings]]
chars = "\u001B[6;2~"
key = "PageDown"
mods = "Shift"

[[keyboard.bindings]]
chars = "\u001B[6;5~"
key = "PageDown"
mods = "Control"

[[keyboard.bindings]]
chars = "\u001B[6~"
key = "PageDown"

[[keyboard.bindings]]
action = "ScrollPageUp"
key = "PageUp"
mode = "~Alt"
mods = "Alt"

[[keyboard.bindings]]
action = "ScrollPageDown"
key = "PageDown"
mode = "~Alt"
mods = "Alt"

[[keyboard.bindings]]
action = "ScrollToTop"
key = "Home"
mode = "~Alt"
mods = "Alt"

[[keyboard.bindings]]
action = "ScrollToBottom"
key = "End"
mode = "~Alt"
mods = "Alt"

[[keyboard.bindings]]
chars = "\u001B[Z"
key = "Tab"
mods = "Shift"

[[keyboard.bindings]]
chars = "\u007F"
key = "Back"

[[keyboard.bindings]]
chars = "\u001B\u007F"
key = "Back"
mods = "Alt"

[[keyboard.bindings]]
chars = "\u001B[2~"
key = "Insert"

[[keyboard.bindings]]
chars = "\u001B[3~"
key = "Delete"

[[keyboard.bindings]]
chars = "\u001B[1;2D"
key = "Left"
mods = "Shift"

[[keyboard.bindings]]
chars = "\u001B[1;5D"
key = "Left"
mods = "Control"

[[keyboard.bindings]]
chars = "\u001B[1;3D"
key = "Left"
mods = "Alt"

[[keyboard.bindings]]
chars = "\u001B[1;4D"
key = "Left"
mods = "Alt|Shift"

[[keyboard.bindings]]
chars = "\u001B[1;6D"
key = "Left"
mods = "Control|Shift"

[[keyboard.bindings]]
chars = "\u001B[1;7D"
key = "Left"
mods = "Control|Alt"

[[keyboard.bindings]]
chars = "\u001B[1;8D"
key = "Left"
mods = "Control|Alt|Shift"

[[keyboard.bindings]]
chars = "\u001B[D"
key = "Left"
mode = "~AppCursor"

[[keyboard.bindings]]
chars = "\u001BOD"
key = "Left"
mode = "AppCursor"

[[keyboard.bindings]]
chars = "\u001B[1;2C"
key = "Right"
mods = "Shift"

[[keyboard.bindings]]
chars = "\u001B[1;5C"
key = "Right"
mods = "Control"

[[keyboard.bindings]]
chars = "\u001B[1;3C"
key = "Right"
mods = "Alt"

[[keyboard.bindings]]
chars = "\u001B[1;4C"
key = "Right"
mods = "Alt|Shift"

[[keyboard.bindings]]
chars = "\u001B[1;6C"
key = "Right"
mods = "Control|Shift"

[[keyboard.bindings]]
chars = "\u001B[1;7C"
key = "Right"
mods = "Control|Alt"

[[keyboard.bindings]]
chars = "\u001B[1;8C"
key = "Right"
mods = "Control|Alt|Shift"

[[keyboard.bindings]]
chars = "\u001B[C"
key = "Right"
mode = "~AppCursor"

[[keyboard.bindings]]
chars = "\u001BOC"
key = "Right"
mode = "AppCursor"

[[keyboard.bindings]]
chars = "\u001B[1;2A"
key = "Up"
mods = "Shift"

[[keyboard.bindings]]
chars = "\u001B[1;5A"
key = "Up"
mods = "Control"

[[keyboard.bindings]]
chars = "\u001B[1;3A"
key = "Up"
mods = "Alt"

[[keyboard.bindings]]
chars = "\u001B[1;4A"
key = "Up"
mods = "Alt|Shift"

[[keyboard.bindings]]
chars = "\u001B[1;6A"
key = "Up"
mods = "Control|Shift"

[[keyboard.bindings]]
chars = "\u001B[1;7A"
key = "Up"
mods = "Control|Alt"

[[keyboard.bindings]]
chars = "\u001B[1;8A"
key = "Up"
mods = "Control|Alt|Shift"

[[keyboard.bindings]]
chars = "\u001B[A"
key = "Up"
mode = "~AppCursor"

[[keyboard.bindings]]
chars = "\u001BOA"
key = "Up"
mode = "AppCursor"

[[keyboard.bindings]]
chars = "\u001B[1;2B"
key = "Down"
mods = "Shift"

[[keyboard.bindings]]
chars = "\u001B[1;5B"
key = "Down"
mods = "Control"

[[keyboard.bindings]]
chars = "\u001B[1;3B"
key = "Down"
mods = "Alt"

[[keyboard.bindings]]
chars = "\u001B[1;4B"
key = "Down"
mods = "Alt|Shift"

[[keyboard.bindings]]
chars = "\u001B[1;6B"
key = "Down"
mods = "Control|Shift"

[[keyboard.bindings]]
chars = "\u001B[1;7B"
key = "Down"
mods = "Control|Alt"

[[keyboard.bindings]]
chars = "\u001B[1;8B"
key = "Down"
mods = "Control|Alt|Shift"

[[keyboard.bindings]]
chars = "\u001B[B"
key = "Down"
mode = "~AppCursor"

[[keyboard.bindings]]
chars = "\u001BOB"
key = "Down"
mode = "AppCursor"

[[keyboard.bindings]]
chars = "±"
key = "Key1"
mods = "Control|Alt"

[[keyboard.bindings]]
chars = "ÿ"
key = "Key8"
mods = "Alt|Control"

[[keyboard.bindings]]
chars = "¹"
key = "Key9"
mods = "Alt|Control"

[[keyboard.bindings]]
chars = "°"
key = "Key0"
mods = "Alt|Control"

[[keyboard.bindings]]
chars = "\u001BOP"
key = "F1"

[[keyboard.bindings]]
chars = "\u001BOQ"
key = "F2"

[[keyboard.bindings]]
chars = "\u001BOR"
key = "F3"

[[keyboard.bindings]]
chars = "\u001BOS"
key = "F4"

[[keyboard.bindings]]
chars = "\u001B[15~"
key = "F5"

[[keyboard.bindings]]
chars = "\u001B[17~"
key = "F6"

[[keyboard.bindings]]
chars = "\u001B[18~"
key = "F7"

[[keyboard.bindings]]
chars = "\u001B[19~"
key = "F8"

[[keyboard.bindings]]
chars = "\u001B[20~"
key = "F9"

[[keyboard.bindings]]
chars = "\u001B[21~"
key = "F10"

[[keyboard.bindings]]
chars = "\u001B[23~"
key = "F11"

[[keyboard.bindings]]
chars = "\u001B[24~"
key = "F12"

[[keyboard.bindings]]
chars = "\u001B[1;2P"
key = "F1"
mods = "Shift"

[[keyboard.bindings]]
chars = "\u001B[1;2Q"
key = "F2"
mods = "Shift"

[[keyboard.bindings]]
chars = "\u001B[1;2R"
key = "F3"
mods = "Shift"

[[keyboard.bindings]]
chars = "\u001B[1;2S"
key = "F4"
mods = "Shift"

[[keyboard.bindings]]
chars = "\u001B[15;2~"
key = "F5"
mods = "Shift"

[[keyboard.bindings]]
chars = "\u001B[17;2~"
key = "F6"
mods = "Shift"

[[keyboard.bindings]]
chars = "\u001B[18;2~"
key = "F7"
mods = "Shift"

[[keyboard.bindings]]
chars = "\u001B[19;2~"
key = "F8"
mods = "Shift"

[[keyboard.bindings]]
chars = "\u001B[20;2~"
key = "F9"
mods = "Shift"

[[keyboard.bindings]]
chars = "\u001B[21;2~"
key = "F10"
mods = "Shift"

[[keyboard.bindings]]
chars = "\u001B[23;2~"
key = "F11"
mods = "Shift"

[[keyboard.bindings]]
chars = "\u001B[24;2~"
key = "F12"
mods = "Shift"

[[keyboard.bindings]]
chars = "\u001B[1;5P"
key = "F1"
mods = "Control"

[[keyboard.bindings]]
chars = "\u001B[1;5Q"
key = "F2"
mods = "Control"

[[keyboard.bindings]]
chars = "\u001B[1;5R"
key = "F3"
mods = "Control"

[[keyboard.bindings]]
chars = "\u001B[1;5S"
key = "F4"
mods = "Control"

[[keyboard.bindings]]
chars = "\u001B[15;5~"
key = "F5"
mods = "Control"

[[keyboard.bindings]]
chars = "\u001B[17;5~"
key = "F6"
mods = "Control"

[[keyboard.bindings]]
chars = "\u001B[18;5~"
key = "F7"
mods = "Control"

[[keyboard.bindings]]
chars = "\u001B[19;5~"
key = "F8"
mods = "Control"

[[keyboard.bindings]]
chars = "\u001B[20;5~"
key = "F9"
mods = "Control"

[[keyboard.bindings]]
chars = "\u001B[21;5~"
key = "F10"
mods = "Control"

[[keyboard.bindings]]
chars = "\u001B[23;5~"
key = "F11"
mods = "Control"

[[keyboard.bindings]]
chars = "\u001B[24;5~"
key = "F12"
mods = "Control"

[[keyboard.bindings]]
chars = "\u001B[1;3P"
key = "F1"
mods = "Alt"

[[keyboard.bindings]]
chars = "\u001B[1;3Q"
key = "F2"
mods = "Alt"

[[keyboard.bindings]]
chars = "\u001B[1;3R"
key = "F3"
mods = "Alt"

[[keyboard.bindings]]
chars = "\u001B[1;3S"
key = "F4"
mods = "Alt"

[[keyboard.bindings]]
chars = "\u001B[15;3~"
key = "F5"
mods = "Alt"

[[keyboard.bindings]]
chars = "\u001B[17;3~"
key = "F6"
mods = "Alt"

[[keyboard.bindings]]
chars = "\u001B[18;3~"
key = "F7"
mods = "Alt"

[[keyboard.bindings]]
chars = "\u001B[19;3~"
key = "F8"
mods = "Alt"

[[keyboard.bindings]]
chars = "\u001B[20;3~"
key = "F9"
mods = "Alt"

[[keyboard.bindings]]
chars = "\u001B[21;3~"
key = "F10"
mods = "Alt"

[[keyboard.bindings]]
chars = "\u001B[23;3~"
key = "F11"
mods = "Alt"

[[keyboard.bindings]]
chars = "\u001B[24;3~"
key = "F12"
mods = "Alt"

[[keyboard.bindings]]
chars = "\u001B[OP"
key = "F1"
mods = "Super"

[[keyboard.bindings]]
chars = "\u001B[OQ"
key = "F2"
mods = "Super"

[[keyboard.bindings]]
chars = "\u001B[OR"
key = "F3"
mods = "Super"

[[keyboard.bindings]]
chars = "\u001B[OS"
key = "F4"
mods = "Super"

[[keyboard.bindings]]
chars = "\u001B[15~"
key = "F5"
mods = "Super"

[[keyboard.bindings]]
chars = "\u001B[17~"
key = "F6"
mods = "Super"

[[keyboard.bindings]]
chars = "\u001B[18~"
key = "F7"
mods = "Super"

[[keyboard.bindings]]
chars = "\u001B[19~"
key = "F8"
mods = "Super"

[[keyboard.bindings]]
chars = "\u001B[20~"
key = "F9"
mods = "Super"

[[keyboard.bindings]]
chars = "\u001B[21~"
key = "F10"
mods = "Super"

[[keyboard.bindings]]
chars = "\u001B[23~"
key = "F11"
mods = "Super"

[[keyboard.bindings]]
chars = "\u001B[24~"
key = "F12"
mods = "Super"

[[keyboard.bindings]]
chars = "\u001B[1;6P"
key = "F1"
mods = "Control|Shift"

[[keyboard.bindings]]
chars = "\u001B[1;6Q"
key = "F2"
mods = "Control|Shift"

[[keyboard.bindings]]
chars = "\u001B[1;6R"
key = "F3"
mods = "Control|Shift"

[[keyboard.bindings]]
chars = "\u001B[1;6S"
key = "F4"
mods = "Control|Shift"

[[keyboard.bindings]]
chars = "\u001B[15;6~"
key = "F5"
mods = "Control|Shift"

[[keyboard.bindings]]
chars = "\u001B[17;6~"
key = "F6"
mods = "Control|Shift"

[[keyboard.bindings]]
chars = "\u001B[18;6~"
key = "F7"
mods = "Control|Shift"

[[keyboard.bindings]]
chars = "\u001B[19;6~"
key = "F8"
mods = "Control|Shift"

[[keyboard.bindings]]
chars = "\u001B[20;6~"
key = "F9"
mods = "Control|Shift"

[[keyboard.bindings]]
chars = "\u001B[21;6~"
key = "F10"
mods = "Control|Shift"

[[keyboard.bindings]]
chars = "\u001B[23;6~"
key = "F11"
mods = "Control|Shift"

[[keyboard.bindings]]
chars = "\u001B[24;6~"
key = "F12"
mods = "Control|Shift"

[[keyboard.bindings]]
chars = "\u001B[1;4P"
key = "F1"
mods = "Alt|Shift"

[[keyboard.bindings]]
chars = "\u001B[1;4Q"
key = "F2"
mods = "Alt|Shift"

[[keyboard.bindings]]
chars = "\u001B[1;4R"
key = "F3"
mods = "Alt|Shift"

[[keyboard.bindings]]
chars = "\u001B[1;4S"
key = "F4"
mods = "Alt|Shift"

[[keyboard.bindings]]
chars = "\u001B[15;4~"
key = "F5"
mods = "Alt|Shift"

[[keyboard.bindings]]
chars = "\u001B[17;4~"
key = "F6"
mods = "Alt|Shift"

[[keyboard.bindings]]
chars = "\u001B[18;4~"
key = "F7"
mods = "Alt|Shift"

[[keyboard.bindings]]
chars = "\u001B[19;4~"
key = "F8"
mods = "Alt|Shift"

[[keyboard.bindings]]
chars = "\u001B[20;4~"
key = "F9"
mods = "Alt|Shift"

[[keyboard.bindings]]
chars = "\u001B[21;4~"
key = "F10"
mods = "Alt|Shift"

[[keyboard.bindings]]
chars = "\u001B[23;4~"
key = "F11"
mods = "Alt|Shift"

[[keyboard.bindings]]
chars = "\u001B[24;4~"
key = "F12"
mods = "Alt|Shift"

[[keyboard.bindings]]
chars = "\u001B[1;7P"
key = "F1"
mods = "Alt|Control"

[[keyboard.bindings]]
chars = "\u001B[1;7Q"
key = "F2"
mods = "Alt|Control"

[[keyboard.bindings]]
chars = "\u001B[1;7R"
key = "F3"
mods = "Alt|Control"

[[keyboard.bindings]]
chars = "\u001B[1;7S"
key = "F4"
mods = "Alt|Control"

[[keyboard.bindings]]
chars = "\u001B[15;7~"
key = "F5"
mods = "Alt|Control"

[[keyboard.bindings]]
chars = "\u001B[17;7~"
key = "F6"
mods = "Alt|Control"

[[keyboard.bindings]]
chars = "\u001B[18;7~"
key = "F7"
mods = "Alt|Control"

[[keyboard.bindings]]
chars = "\u001B[19;7~"
key = "F8"
mods = "Alt|Control"

[[keyboard.bindings]]
chars = "\u001B[20;7~"
key = "F9"
mods = "Alt|Control"

[[keyboard.bindings]]
chars = "\u001B[21;7~"
key = "F10"
mods = "Alt|Control"

[[keyboard.bindings]]
chars = "\u001B[23;7~"
key = "F11"
mods = "Alt|Control"

[[keyboard.bindings]]
chars = "\u001B[24;7~"
key = "F12"
mods = "Alt|Control"

[[keyboard.bindings]]
chars = "\u001B[1;8P"
key = "F1"
mods = "Alt|Control|Shift"

[[keyboard.bindings]]
chars = "\u001B[1;8Q"
key = "F2"
mods = "Alt|Control|Shift"

[[keyboard.bindings]]
chars = "\u001B[1;8R"
key = "F3"
mods = "Alt|Control|Shift"

[[keyboard.bindings]]
chars = "\u001B[1;8S"
key = "F4"
mods = "Alt|Control|Shift"

[[keyboard.bindings]]
chars = "\u001B[15;8~"
key = "F5"
mods = "Alt|Control|Shift"

[[keyboard.bindings]]
chars = "\u001B[17;8~"
key = "F6"
mods = "Alt|Control|Shift"

[[keyboard.bindings]]
chars = "\u001B[18;8~"
key = "F7"
mods = "Alt|Control|Shift"

[[keyboard.bindings]]
chars = "\u001B[19;8~"
key = "F8"
mods = "Alt|Control|Shift"

[[keyboard.bindings]]
chars = "\u001B[20;8~"
key = "F9"
mods = "Alt|Control|Shift"

[[keyboard.bindings]]
chars = "\u001B[21;8~"
key = "F10"
mods = "Alt|Control|Shift"

[[keyboard.bindings]]
chars = "\u001B[23;8~"
key = "F11"
mods = "Alt|Control|Shift"

[[keyboard.bindings]]
chars = "\u001B[24;8~"
key = "F12"
mods = "Alt|Control|Shift"

[mouse]
hide_when_typing = false

[[mouse.bindings]]
action = "PasteSelection"
mouse = "Middle"

[scrolling]
history = 10000
multiplier = 3

[selection]
save_to_clipboard = false
semantic_escape_chars = ",│`|:\"' ()[]{}<>="

[window]
decorations = "full"
dynamic_padding = false
dynamic_title = true
opacity = 1.0
startup_mode = "Windowed"

[window.dimensions]
columns = 0
lines = 0

[window.padding]
x = 0
y = 0
