name: Check Neovim Plugins

on:
  schedule:
    - cron: "0 0 * * 1"
  workflow_dispatch:

permissions:
  contents: read
  issues: write

jobs:
  check-neovim-plugins:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Neovim config
        uses: actions/checkout@v6

      - name: Check plugins
        uses: yutkat/lazy-nvim-archived-checker@v1
        with:
          nvim-config-path: ${{ github.workspace }}/.config/nvim/
